
services:
  gestion_de_entradas:
    image: gestion_de_entradas
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion_de_entradas
    ports:
      - "8001:80"
    volumes:
      - ./app:/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
    depends_on:
      gestion_db:
        condition: service_healthy
    networks:
      - default

  gestion_db:
    image: mariadb:11.8.1-ubi9-rc
    restart: unless-stopped
    container_name: gestion_db
    ports:
      - 3330:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u$${MARIADB_USER} -p$${MARIADB_PASSWORD} -e 'SHOW DATABASES;'"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: nginx-gestion
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
      - ./app/media:/app/media
    depends_on:
      - gestion_de_entradas
    networks:
      - default

volumes:
  db:

networks:
  default:
    driver: bridge
